### ISSUE TITLE
 PaperTrail.update fails at setting the item_changes for versions when struct include nested ecto changeset for assoc

### ISSUE THREAD

**Issue by digitalcake** [izelnakri/paper_trail#38] opened 2018-02-14 23:52 UTC
when trying to update a valid changeset I get some odd errors the call out an issue on the associated recorders. 

Note: the changeset is valid. 
```
client |> Client.changeset(attrs)
#Ecto.Changeset<
  action: nil,
  changes: %{
    first_name: "Test",
    phone_numbers: [
      #Ecto.Changeset<
        action: :insert,
        changes: %{notes: "asdf", number: "555-555", type: "Home"},
        errors: [],
        data: #Beffect.Intake.Client.PhoneNumber<>,
        valid?: true
      >
    ]
  },
  errors: [],
  data: #Beffect.Intake.Client<>,
  valid?: true 
>

pry(4)> client |> Client.changeset(attrs) |> PaperTrail.update(originator: user)
iex(1)> [debug] QUERY OK db=0.2ms
begin []
[debug] QUERY OK db=5.0ms
UPDATE "clients" SET "first_name" = $1, "updated_at" = $2 WHERE "id" = $3 ["Test", {{2018, 2, 14}, {23, 44, 15, 517011}}, 27]
[debug] QUERY OK db=2.0ms
INSERT INTO "client_phone_numbers" ("can_message","client_id","notes","number","preferred","type","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING "id" [false, 27, "asdf", "555-5555", false, "Home", {{2018, 2, 14}, {23, 44, 15, 525806}}, {{2018, 2, 14}, {23, 44, 15, 525815}}]
[debug] QUERY ERROR db=8.7ms
INSERT INTO "versions" ("event","item_changes","item_id","item_type","originator_id","inserted_at") VALUES ($1,$2,$3,$4,$5,$6) RETURNING "id", "origin" ["update", %{first_name: "Test", phone_numbers: [#Ecto.Changeset<action: :insert, changes: %{notes: "asdf", number: "555-5555", type: "Home"}, errors: [], data: #Beffect.Intake.Client.PhoneNumber<>, valid?: true>]}, 27, "Client", 1, {{2018, 2, 14}, {23, 44, 15, 530146}}]
[debug] QUERY OK db=0.9ms
rollback []
** (Poison.EncodeError) unable to encode value: {nil, "client_phone_numbers"}
    (poison) lib/poison/encoder.ex:383: Poison.Encoder.Any.encode/2
    (poison) lib/poison/encoder.ex:227: anonymous fn/4 in Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:227: anonymous fn/4 in Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:227: anonymous fn/4 in Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:259: anonymous fn/3 in Poison.Encoder.List.encode/3
    (poison) lib/poison/encoder.ex:260: Poison.Encoder.List.encode/3
    (poison) lib/poison/encoder.ex:227: anonymous fn/4 in Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map.encode/3
    (poison) lib/poison.ex:41: Poison.encode!/2
    (ecto) /Users/joshchernoff/Dev/elixir/beffect/deps/postgrex/lib/postgrex/type_module.ex:717: Ecto.Adapters.Postgres.TypeModule.encode_params/3
    (postgrex) lib/postgrex/query.ex:45: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection) lib/db_connection.ex:1079: DBConnection.describe_run/5
    (db_connection) lib/db_connection.ex:1150: anonymous fn/4 in DBConnection.run_meter/5
```

heres how I build the assoc
```
has_many(
      :phone_numbers,
      Beffect.Intake.Client.PhoneNumber,
      on_delete: :delete_all
    )
```
I'm not doing much other than just simply
` |> cast_assoc(:phone_numbers)`
with my change set

vars:

client =
```
%Beffect.Intake.Client{
  __meta__: #Ecto.Schema.Metadata<:loaded, "clients">,
  phone_numbers: [],
  ...
}
```

attrs = 
```
%{
  ...
  "phone_numbers" => %{
    "0" => %{"notes" => "asdf", "number" => "555-5555", "type" => "Home"}
  }
}
```

**Comment by digitalcake** [comment] 2018-02-15 00:13
I'd like to note that this is only for update. Insert works with the same changeset

**Comment by digitalcake** [comment] 2018-02-15 00:22
Also noticing that version's item_changes does not include a ref to the assoc so I'm wondering why the update looks to be trying to insert phone_numbers ?

**Comment by digitalcake** [comment] 2018-02-15 00:38
It looks to be related to how insert deals with serializing out the assoc on insert but does not do the same for update.

Its an interesting problem in that if you are only updating the assoc then what should you be putting in the versions?

**Comment by digitalcake** [comment] 2018-02-15 00:42
The changeset.changes includes  an #Ecto.Changeset inside the struct.  https://github.com/izelnakri/paper_trail/blob/0e978bf6e066802bcbbe1dc0a546a0c92d6b2052/lib/paper_trail.ex#L256

this is what my changeset.changes looks like
```
%{
  first_name: "Test",
  phone_numbers: [
    #Ecto.Changeset<
      action: :insert,
      changes: %{notes: "asdf", number: "9715709721", type: "Home"},
      errors: [],
      data: #Beffect.Intake.Client.PhoneNumber<>,
      valid?: true
    >
  ]
}
```

I believe this to be the issue.

**Comment by izelnakri** [comment] 2018-02-15 20:06
I'm closing this issue as it is it duplicate of https://github.com/izelnakri/paper_trail/issues/39

**Closed by izelnakri** 2018-02-15 20:06 UTC
